const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('./database/colors.db');

db.serialize(() => {
  db.run("DROP TABLE IF EXISTS colors");
  db.run("CREATE TABLE colors (id INTEGER PRIMARY KEY, name TEXT UNIQUE, hex TEXT)");

  const colors = [
    {name:'aliceblue', hex:'#f0f8ff'},
    {name:'antiquewhite', hex:'#faebd7'},
    {name:'aqua', hex:'#00ffff'},
    {name:'aquamarine', hex:'#7fffd4'},
    {name:'azure', hex:'#f0ffff'},
    {name:'beige', hex:'#f5f5dc'},
    {name:'bisque', hex:'#ffe4c4'},
    {name:'black', hex:'#000000'},
    {name:'blanchedalmond', hex:'#ffebcd'},
    {name:'blue', hex:'#0000ff'},
    {name:'blueviolet', hex:'#8a2be2'},
    {name:'brown', hex:'#a52a2a'},
    {name:'burlywood', hex:'#deb887'},
    {name:'cadetblue', hex:'#5f9ea0'},
    {name:'chartreuse', hex:'#7fff00'},
    {name:'chocolate', hex:'#d2691e'},
    {name:'coral', hex:'#ff7f50'},
    {name:'cornflowerblue', hex:'#6495ed'},
    {name:'cornsilk', hex:'#fff8dc'},
    {name:'crimson', hex:'#dc143c'},
    {name:'cyan', hex:'#00ffff'},
    {name:'darkblue', hex:'#00008b'},
    {name:'darkcyan', hex:'#008b8b'},
    {name:'darkgoldenrod', hex:'#b8860b'},
    {name:'darkgray', hex:'#a9a9a9'},
    {name:'darkgreen', hex:'#006400'},
    {name:'darkkhaki', hex:'#bdb76b'},
    {name:'darkmagenta', hex:'#8b008b'},
    {name:'darkolivegreen', hex:'#556b2f'},
    {name:'darkorange', hex:'#ff8c00'},
    {name:'darkorchid', hex:'#9932cc'},
    {name:'darkred', hex:'#8b0000'},
    {name:'darksalmon', hex:'#e9967a'},
    {name:'darkseagreen', hex:'#8fbc8f'},
    {name:'darkslateblue', hex:'#483d8b'},
    {name:'darkslategray', hex:'#2f4f4f'},
    {name:'darkturquoise', hex:'#00ced1'},
    {name:'darkviolet', hex:'#9400d3'},
    {name:'deeppink', hex:'#ff1493'},
    {name:'deepskyblue', hex:'#00bfff'},
    {name:'dimgray', hex:'#696969'},
    {name:'dodgerblue', hex:'#1e90ff'},
    {name:'firebrick', hex:'#b22222'},
    {name:'floralwhite', hex:'#fffaf0'},
    {name:'forestgreen', hex:'#228b22'},
    {name:'fuchsia', hex:'#ff00ff'},
    {name:'gainsboro', hex:'#dcdcdc'},
    {name:'ghostwhite', hex:'#f8f8ff'},
    {name:'gold', hex:'#ffd700'},
    {name:'goldenrod', hex:'#daa520'},
    {name:'gray', hex:'#808080'},
    {name:'green', hex:'#008000'},
    {name:'greenyellow', hex:'#adff2f'},
    {name:'honeydew', hex:'#f0fff0'},
    {name:'hotpink', hex:'#ff69b4'},
    {name:'indianred', hex:'#cd5c5c'},
    {name:'indigo', hex:'#4b0082'},
    {name:'ivory', hex:'#fffff0'},
    {name:'khaki', hex:'#f0e68c'},
    {name:'lavender', hex:'#e6e6fa'},
    {name:'lavenderblush', hex:'#fff0f5'},
    {name:'lawngreen', hex:'#7cfc00'},
    {name:'lemonchiffon', hex:'#fffacd'},
    {name:'lightblue', hex:'#add8e6'},
    {name:'lightcoral', hex:'#f08080'},
    {name:'lightcyan', hex:'#e0ffff'},
    {name:'lightgoldenrodyellow', hex:'#fafad2'},
    {name:'lightgray', hex:'#d3d3d3'},
    {name:'lightgreen', hex:'#90ee90'},
    {name:'lightpink', hex:'#ffb6c1'},
    {name:'lightsalmon', hex:'#ffa07a'},
    {name:'lightseagreen', hex:'#20b2aa'},
    {name:'lightskyblue', hex:'#87cefa'},
    {name:'lightslategray', hex:'#778899'},
    {name:'lightsteelblue', hex:'#b0c4de'},
    {name:'lime', hex:'#00ff00'},
    {name:'limegreen', hex:'#32cd32'},
    {name:'linen', hex:'#faf0e6'},
    {name:'magenta', hex:'#ff00ff'},
    {name:'maroon', hex:'#800000'},
    {name:'mediumaquamarine', hex:'#66cdaa'},
    {name:'mediumblue', hex:'#0000cd'},
  ];

  const stmt = db.prepare("INSERT INTO colors (name, hex) VALUES (?, ?)");
  colors.forEach(c => stmt.run(c.name, c.hex));
  stmt.finalize();

  console.log("✅ Colors imported into SQLite!");
});

db.close();
